### ISSUE TITLE
运行downloadTorrent.py  出错

### ISSUE THREAD

**Issue by Richrain** [NanYoMy/DHT-woodworm#3]
[root@localhost DHT-woodworm]# python downloadTorrent.py 
Traceback (most recent call last):
  File "downloadTorrent.py", line 120, in <module>
    getAllTorrents("hash_info")
  File "downloadTorrent.py", line 45, in getAllTorrents
    except WindowsError,e:
NameError: global name 'WindowsError' is not defined

**Comment by NanYoMy** [comment]
downloadTorret代码是从网上获取种子资源的。好像那个网站现在挂了。你再看一下，。
