### ISSUE TITLE
抓取hash值期间总是会报错

### ISSUE THREAD

**Issue by Richrain** [NanYoMy/DHT-woodworm#4]
Exception happened during processing of request from ('78.37.74.47', 27200)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/SocketServer.py", line 582, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 323, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python2.7/SocketServer.py", line 639, in **init**
    self.handle()
  File "/opt/DHT-woodworm/btdht/btdht.py", line 37, in handle
    msg_type = message["y"]
KeyError: 'y

**Comment by NanYoMy** [comment]
try except一下

发自我的 Windows Phone

---

发件人: Richmailto:notifications@github.com
发送时间: ‎2015/‎6/‎24 0:08
收件人: NanYoMy/DHT-woodwormmailto:DHT-woodworm@noreply.github.com
主题: [DHT-woodworm] 抓取hash值期间总是会报错 (#4)

Exception happened during processing of request from ('78.37.74.47', 27200)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/SocketServer.py", line 582, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 323, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python2.7/SocketServer.py", line 639, in **init**
    self.handle()
  File "/opt/DHT-woodworm/btdht/btdht.py", line 37, in handle
    msg_type = message["y"]
KeyError: 'y

---

Reply to this email directly or view it on GitHub:
https://github.com/NanYoMy/DHT-woodworm/issues/4
